### PR TITLE
fixes #315 - change hardcoded unix line separator to OS independent

### LINKED ISSUE #315: ReadError.prettyPrint isn't platform independent
`sbt test` run on Windows 10 (64) shows tests related with `prettyPrint` red. 

```[info] - ReadErrors/NEL
[info]   - prettyPrint of complex ReadError full text
[info]     Test failed after 1 iteration with input: (AndErrors(List(MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))), FormatError(List(Key(k1), Key(k2)), Format error), ConversionError(List(Key(k1), Key(k2)),Conversion error, OrErrors(List(AndErrors(List(OrErrors(List(MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))), MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))))), FormatError(List(Key(k1), Key(k2)), Format error)), OrErrors(List(MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))), MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))))), ConversionError(List(Key(k1), Key(k2)),Conversion error)), AndErrors(List(OrErrors(List(MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))), MissingValue(List(Key(k1), Key(k2), Index(1), Key(k3))))), FormatError(List(Key(k1), Key(k2)), Format error))),ReadError failed.
[info] ╥
[info] ╠══╦══╦══╦══╦══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║
[info] ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ▼
[info] ║  ║  ║
[info] ║  ║  ╠─FormatError
[info] ║  ║  ║ cause: Format error
[info] ║  ║  ║ path: k1.k2
[info] ║  ║  ▼
[info] ║  ║
[info] ║  ╠─MissingValue
[info] ║  ║ path: k1.k2[1].k3
[info] ║  ▼
[info] ▼)
[info]     ReadError failed.
[info] ╥
[info] ╠══╦══╦══╦══╦══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║
[info] ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ▼
[info] ║  ║  ║
[info] ║  ║  ╠─FormatError
[info] ║  ║  ║ cause: Format error
[info] ║  ║  ║ path: k1.k2
[info] ║  ║  ▼
[info] ║  ║
[info] ║  ╠─MissingValue
[info] ║  ║ path: k1.k2[1].k3
[info] ║  ▼
[info] ▼ did not satisfy equalTo(ReadError failed.
[info] ╥
[info] ╠══╦══╦══╦══╦══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠══╦══╗
[info] ║  ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ║  ╠─FormatError
[info] ║  ║  ║  ║  ║  ║  ║ cause: Format error
[info] ║  ║  ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─MissingValue
[info] ║  ║  ║  ║  ║ path: k1.k2[1].k3
[info] ║  ║  ║  ║  ║
[info] ║  ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ║  ▼
[info] ║  ║  ║  ║
[info] ║  ║  ║  ╠─ConversionError
[info] ║  ║  ║  ║ cause: Conversion error
[info] ║  ║  ║  ║ path: k1.k2
[info] ║  ║  ║  ▼
[info] ║  ║  ║
[info] ║  ║  ╠─FormatError
[info] ║  ║  ║ cause: Format error
[info] ║  ║  ║ path: k1.k2
[info] ║  ║  ▼
[info] ║  ║
[info] ║  ╠─MissingValue
[info] ║  ║ path: k1.k2[1].k3
[info] ║  ▼
[info] ▼)
```

I've found that at the end of the function is `mkString("\n")` which is line ending for *nix systems, but not valid for Windows, thats why comparision fails.

All what has to be done is to replace hardcoded "\n" with `System.lineSeparator()` to make all tests green.

### PR DESCRIPTION
**Pull request by marioosh**
#315 ReadError.prettyPrint on WIndows 10 issue

### CODE REVIEW

File: core/src/main/scala/zio/config/ReadError.scala [hunk 1]
```diff
@@ -138,7 +138,7 @@ sealed trait ReadError[A] extends Exception { self =>
 
         case _ => format(sequence).updated(0, "╥")
       }
-    }).mkString("\n")
+    }).mkString(System.lineSeparator())
```
Comment (afsalthaj) [inline core/src/main/scala/zio/config/ReadError.scala:141]: Should we be using `zio.lineSeparator` ?

Advantage: Seamless integration with zio
Disadvantage: Currently zoo-config allows users to retrieve config as a simple Either[ReadError, A]. It won't be user-friendly if they end up having to deal with effect system just to prettyPrint their errors.

@jdegoes  @senia-psm  Any views on this?

**Comment by afsalthaj** [comment]
@marioosh Nice catch by the way. Thanks for your PR.

File: core/src/main/scala/zio/config/ReadError.scala (hunk 1 above)
Comment (jdegoes) [reply core/src/main/scala/zio/config/ReadError.scala:141]: Probably ZIO should change to make line separator static, assuming it is guaranteed to be static on the JVM. In the meantime, fine to use System.lineSeparator() here.
