### PR TITLE
Fix test case in args source

### LINKED ISSUE #246: Accumulate list contents by multiple cmd line args with same key

### PR DESCRIPTION
**Pull request by afsalthaj**
Fixes #246 

Also `--key` is not an empty list. It is a missing value, that nothing is provided for the key `key`.
Hence property test for args is changes from `0 until count` to `1 to count` for generating random lists

### CODE REVIEW

File: core/src/main/scala/zio/config/ConfigSource.scala [hunk 1]
```diff
@@ -51,10 +51,14 @@ object ConfigSource {
     valueDelimiter: Option[Char]
   ): UIO[ConfigSource[String, String]] =
     UIO.effectTotal(argsAsKeyValues(args)).map { kvs =>
-      mergeAll(
-        kvs.map { kv =>
-          fromMapInternal(Map(kv))(splitDelimited(_, valueDelimiter), keyDelimiter, "command line arg")
-        }
+      ConfigSource.fromPropertyTrees(
```
Comment (leigh-perry) [inline core/src/main/scala/zio/config/ConfigSource.scala:54]: https://github.com/zio/zio-config/issues/248
you can get rid of UIO where modifying this method

File: core/src/main/scala/zio/config/ConfigSource.scala [hunk 2]
```diff
@@ -51,10 +51,14 @@ object ConfigSource {
...
+        PropertyTree.mergeAll(
+          kvs.map {
+            case (str, str1) =>
```
Comment (leigh-perry) [inline core/src/main/scala/zio/config/ConfigSource.scala:57]: key, value instead of str, str1
:-)

File: core/src/test/scala/zio/config/ArgsListAccumulationTest.scala [hunk 3]
```diff
@@ -0,0 +1,41 @@
+package zio.config
+
+import zio.ZIO
+import zio.config.ConfigDescriptor.{ int, list }
+import zio.test.Assertion._
+import zio.test.environment.TestEnvironment
+import zio.test.{ DefaultRunnableSpec, _ }
+
+object ArgsListAccumulationTest extends DefaultRunnableSpec {
```
Comment (leigh-perry) [inline core/src/test/scala/zio/config/ArgsListAccumulationTest.scala:9]: My idea for this test was to test all the applicable input media, like properties, args etc.
`ArgsListAccumulationTest` should be `ListAccumulationTest`

File: core/src/main/scala/zio/config/ConfigSource.scala (hunk 1 above)
Comment (afsalthaj) [reply core/src/main/scala/zio/config/ConfigSource.scala:54]: Yea sure

File: core/src/test/scala/zio/config/ArgsListAccumulationTest.scala (hunk 3 above)
Comment (afsalthaj) [reply core/src/test/scala/zio/config/ArgsListAccumulationTest.scala:9]: Not sure. You were using a different set of combinators + logic to form the args source which is unlike properties, hocon.

Comment (afsalthaj) [reply core/src/test/scala/zio/config/ArgsListAccumulationTest.scala:9]: If the assumption was, every source is a map, then we have a single test case. But its not the case.

Comment (afsalthaj) [reply core/src/test/scala/zio/config/ArgsListAccumulationTest.scala:9]: For example, the above logic for command line args, we are not using Map anymore.
Or to put it this way, every source has their own way of forming the tree.
For example the way we form the tree from hocon isn't the same as we form the tree from a map/sys.env.

Hence we need to test per source.

Ideally, combinators in PropertyTree are proven to be working. But whether the source is making use of the correct combinators lead to testing them

Comment (afsalthaj) [reply core/src/test/scala/zio/config/ArgsListAccumulationTest.scala:9]: PropertyTree.mergeAll was missing from ArgsSource. Now that we added, and we test that explicitly.

File: core/src/main/scala/zio/config/ConfigSource.scala (hunk 2 above)
Comment (afsalthaj) [reply core/src/main/scala/zio/config/ConfigSource.scala]: auto-complete from intellij. fixed

**Comment by afsalthaj** [comment]
We will have another follow up PR that avoids some restrictions (being able to use only k=v version) in CommandLine
